// <auto-generated />
using System;
using FabricaPastas.BD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FabricaPastas.BD.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260221053258_ini")]
    partial class ini
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Categoria_Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categoria_Producto");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Detalle_Lista_Precio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Lista_Precio_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("Lista_Precio_Id", "Producto_Id")
                        .IsUnique();

                    b.ToTable("Detalle_Lista_Precio");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Detalle_Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Pedido_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Unitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Pedido_Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("Producto_Id");

                    b.ToTable("Detalle_Pedido");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Estado_Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("Estado_Pedido");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Forma_Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Metodo")
                        .IsUnique();

                    b.ToTable("Forma_Pago");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Lista_Precio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Tipo")
                        .IsUnique();

                    b.ToTable("Lista_Precio");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Metodo_Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("Metodo_Entrega");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPedido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Estado_PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado_Pedido_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Forma_PagoId")
                        .HasColumnType("int");

                    b.Property<int>("Forma_Pago_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Metodo_EntregaId")
                        .HasColumnType("int");

                    b.Property<int>("Metodo_Entrega_Id")
                        .HasColumnType("int");

                    b.Property<string>("ObservacionesCatering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPedido")
                        .IsUnique();

                    b.HasIndex("Estado_PedidoId");

                    b.HasIndex("Estado_Pedido_Id");

                    b.HasIndex("FechaPedido");

                    b.HasIndex("Forma_PagoId");

                    b.HasIndex("Forma_Pago_Id");

                    b.HasIndex("Metodo_EntregaId");

                    b.HasIndex("Metodo_Entrega_Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CategoriaProductoId");

                    b.HasIndex("Nombre");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Promocion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Descuento_Porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Fecha_Fin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Fecha_Inicio")
                        .HasColumnType("date");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Promocion");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Promocion_Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.Property<int?>("PromocionId")
                        .HasColumnType("int");

                    b.Property<int>("Promocion_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("PromocionId");

                    b.HasIndex("Promocion_Id", "Producto_Id")
                        .IsUnique();

                    b.ToTable("Promocion_Producto");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Promocion_Rango", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Descuento_Porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaxPedidos")
                        .HasColumnType("int");

                    b.Property<int>("MinPedidos")
                        .HasColumnType("int");

                    b.Property<int>("Promocion_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Tipo_Cliente_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Tipo_Cliente_Id");

                    b.HasIndex("Promocion_Id", "Tipo_Cliente_Id", "MinPedidos", "MaxPedidos");

                    b.ToTable("Promocion_Rango");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Tipo_Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("Tipo_Cliente");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Cuit_Cuil")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Lista_Precio_Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol_Id")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tipo_Cliente_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Lista_Precio_Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("Rol_Id");

                    b.HasIndex("Tipo_Cliente_Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Detalle_Lista_Precio", b =>
                {
                    b.HasOne("FabricaPastas.BD.Data.Entity.Lista_Precio", "Lista_Precio")
                        .WithMany("Detalles")
                        .HasForeignKey("Lista_Precio_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FabricaPastas.BD.Data.Entity.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.Navigation("Lista_Precio");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Detalle_Pedido", b =>
                {
                    b.HasOne("FabricaPastas.BD.Data.Entity.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("Pedido_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FabricaPastas.BD.Data.Entity.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Pedido", b =>
                {
                    b.HasOne("FabricaPastas.BD.Data.Entity.Estado_Pedido", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("Estado_PedidoId");

                    b.HasOne("FabricaPastas.BD.Data.Entity.Estado_Pedido", "Estado_Pedido")
                        .WithMany()
                        .HasForeignKey("Estado_Pedido_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FabricaPastas.BD.Data.Entity.Forma_Pago", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("Forma_PagoId");

                    b.HasOne("FabricaPastas.BD.Data.Entity.Forma_Pago", "Forma_Pago")
                        .WithMany()
                        .HasForeignKey("Forma_Pago_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FabricaPastas.BD.Data.Entity.Metodo_Entrega", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("Metodo_EntregaId");

                    b.HasOne("FabricaPastas.BD.Data.Entity.Metodo_Entrega", "Metodo_Entrega")
                        .WithMany()
                        .HasForeignKey("Metodo_Entrega_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FabricaPastas.BD.Data.Entity.Usuario", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId");

                    b.HasOne("FabricaPastas.BD.Data.Entity.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado_Pedido");

                    b.Navigation("Forma_Pago");

                    b.Navigation("Metodo_Entrega");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Producto", b =>
                {
                    b.HasOne("FabricaPastas.BD.Data.Entity.Categoria_Producto", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Promocion_Producto", b =>
                {
                    b.HasOne("FabricaPastas.BD.Data.Entity.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.HasOne("FabricaPastas.BD.Data.Entity.Promocion", "Promocion")
                        .WithMany("Productos")
                        .HasForeignKey("PromocionId");

                    b.Navigation("Producto");

                    b.Navigation("Promocion");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Promocion_Rango", b =>
                {
                    b.HasOne("FabricaPastas.BD.Data.Entity.Promocion", "Promocion")
                        .WithMany("Rangos")
                        .HasForeignKey("Promocion_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FabricaPastas.BD.Data.Entity.Tipo_Cliente", "Tipo_Cliente")
                        .WithMany()
                        .HasForeignKey("Tipo_Cliente_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Promocion");

                    b.Navigation("Tipo_Cliente");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Usuario", b =>
                {
                    b.HasOne("FabricaPastas.BD.Data.Entity.Lista_Precio", "Lista_Precio")
                        .WithMany()
                        .HasForeignKey("Lista_Precio_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FabricaPastas.BD.Data.Entity.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("Rol_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FabricaPastas.BD.Data.Entity.Tipo_Cliente", "Tipo_Cliente")
                        .WithMany("Usuarios")
                        .HasForeignKey("Tipo_Cliente_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lista_Precio");

                    b.Navigation("Rol");

                    b.Navigation("Tipo_Cliente");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Categoria_Producto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Estado_Pedido", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Forma_Pago", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Lista_Precio", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Metodo_Entrega", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Promocion", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("Rangos");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Tipo_Cliente", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Usuario", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
